"""Learning FAQ loop — doc feedback (Issue #19).

Persistent "was this helpful?" votes per documentation section, deduped per
tenant (one vote per section — re-votes overwrite, never duplicate rows).
Feeds two consumers:

  1. The dashboard widget: POST /api/docs/feedback + GET /api/docs/feedback
     (my votes, to restore the thumbs state across module switches).
  2. The Admin panel: GET /api/admin/docs-feedback — per-section helpful %,
     totals, and the *recurring questions* list (non-empty comments typed
     when a section got a thumbs-down). Those questions are the input to the
     documented loop: recurring question → new FAQ entry (CONTRIBUTING.md).

Privacy: comments are free text typed by tenants; the admin summary is
localhost/operator-key gated and tenant ids are masked in the output.
"""

import logging
import re
import sqlite3
import time

from services.db import get_db

log = logging.getLogger("cypher65.doc_feedback")

# Section ids are generated by the dashboard template (#docs-overview,
# #docs-faq, …) — a strict whitelist-ish shape blocks junk rows.
_SECTION_RE = re.compile(r"^[a-z0-9_-]{1,64}$")

_COMMENT_MAX = 500
_TENANT_MASK_LEN = 6


def ensure_table():
    """Create the doc_feedback table if missing (idempotent)."""
    conn = get_db()
    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS doc_feedback (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tenant_id TEXT NOT NULL,
                section_id TEXT NOT NULL,
                helpful INTEGER NOT NULL,
                comment TEXT DEFAULT '',
                created_at INTEGER NOT NULL,
                updated_at INTEGER NOT NULL,
                UNIQUE(tenant_id, section_id)
            )
            """
        )
        conn.execute(
            "CREATE INDEX IF NOT EXISTS idx_doc_feedback_section "
            "ON doc_feedback(section_id)"
        )
        conn.commit()
    except sqlite3.Error as e:
        log.warning("[doc_feedback] ensure_table error: %s", e)
    finally:
        conn.close()


def is_valid_section(section_id: str) -> bool:
    """Validate a section id from the client (shape check only)."""
    if not isinstance(section_id, str):
        return False
    return bool(_SECTION_RE.match(section_id))


def record_doc_feedback(
    section_id: str,
    helpful: bool,
    comment: str = "",
    tenant_id: str = "default",
) -> bool:
    """Upsert a vote for (tenant_id, section_id).

    Re-voting overwrites the previous answer and merges a new comment if the
    caller typed one (a fresh comment on a re-vote is appended to keep the
    recurring-questions signal complete). Returns True on success.
    """
    if not is_valid_section(section_id):
        return False
    now = int(time.time())
    comment = (comment or "").strip()[:_COMMENT_MAX]
    conn = get_db()
    try:
        row = conn.execute(
            "SELECT comment FROM doc_feedback "
            "WHERE tenant_id = ? AND section_id = ?",
            (tenant_id, section_id),
        ).fetchone()
        merged = comment
        if row and row["comment"] and comment:
            merged = f"{row['comment']} | {comment}"[:_COMMENT_MAX]
        elif row and row["comment"]:
            merged = row["comment"]
        conn.execute(
            """
            INSERT INTO doc_feedback
                (tenant_id, section_id, helpful, comment, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?)
            ON CONFLICT(tenant_id, section_id) DO UPDATE SET
                helpful = excluded.helpful,
                comment = excluded.comment,
                updated_at = excluded.updated_at
            """,
            (tenant_id, section_id, 1 if helpful else 0, merged, now, now),
        )
        conn.commit()
        return True
    except sqlite3.Error as e:
        log.warning("[doc_feedback] record error: %s", e)
        return False
    finally:
        conn.close()


def my_doc_feedback(tenant_id: str = "default"):
    """Return the current tenant's votes as [{section_id, helpful}].

    Lets the widget restore the 👍/👎 state without a page reload.
    """
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT section_id, helpful FROM doc_feedback WHERE tenant_id = ?",
            (tenant_id,),
        ).fetchall()
        return [
            {"section_id": r["section_id"], "helpful": bool(r["helpful"])} for r in rows
        ]
    except sqlite3.Error as e:
        log.warning("[doc_feedback] my_votes error: %s", e)
        return []
    finally:
        conn.close()


def _mask_tenant(tenant_id: str) -> str:
    """Mask the tenant id for the admin summary (PII-light by default)."""
    t = tenant_id or "default"
    if t == "default" or len(t) <= _TENANT_MASK_LEN:
        return t
    return t[:_TENANT_MASK_LEN] + "…"


def doc_feedback_summary():
    """Aggregate feedback across all tenants for the Admin panel.

    Returns:
        {
          "total_votes": int,
          "sections_with_feedback": int,
          "overall_helpful_pct": float | None,   # None when no votes
          "sections": [  # sorted by total desc, then section id
              {section_id, total, helpful, not_helpful, helpful_pct, updated_at}
          ],
          "recurring_questions": [  # newest first, comments only
              {section_id, tenant, comment, ts}
          ],
        }
    """
    conn = get_db()
    try:
        rows = conn.execute(
            "SELECT tenant_id, section_id, helpful, comment, updated_at "
            "FROM doc_feedback"
        ).fetchall()
    except sqlite3.Error as e:
        log.warning("[doc_feedback] summary error: %s", e)
        return {
            "total_votes": 0,
            "sections_with_feedback": 0,
            "overall_helpful_pct": None,
            "sections": [],
            "recurring_questions": [],
        }
    finally:
        conn.close()

    per_section = {}
    questions = []
    for r in rows:
        s = per_section.setdefault(
            r["section_id"],
            {
                "section_id": r["section_id"],
                "total": 0,
                "helpful": 0,
                "not_helpful": 0,
                "updated_at": r["updated_at"],
            },
        )
        s["total"] += 1
        s["helpful"] += 1 if r["helpful"] else 0
        s["not_helpful"] += 0 if r["helpful"] else 1
        s["updated_at"] = max(s["updated_at"], r["updated_at"])
        if r["comment"]:
            questions.append(
                {
                    "section_id": r["section_id"],
                    "tenant": _mask_tenant(r["tenant_id"]),
                    "comment": r["comment"],
                    "ts": r["updated_at"],
                }
            )

    sections = []
    for s in per_section.values():
        s["helpful_pct"] = (
            round(s["helpful"] / s["total"] * 100.0, 1) if s["total"] else None
        )
        sections.append(s)
    sections.sort(key=lambda s: (-s["total"], s["section_id"]))
    questions.sort(key=lambda q: q["ts"], reverse=True)

    total_votes = sum(s["total"] for s in sections)
    helpful = sum(s["helpful"] for s in sections)
    return {
        "total_votes": total_votes,
        "sections_with_feedback": len(sections),
        "overall_helpful_pct": (
            round(helpful / total_votes * 100.0, 1) if total_votes else None
        ),
        "sections": sections,
        "recurring_questions": questions[:100],
    }
